# Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fluxai-gateway'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
